apiVersion: v1
kind: Namespace
metadata:
  name: chegueni-ouadid-benabdelaziz

---
# 1. Redis (ReplicaSet + Service)
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-rs
  namespace: chegueni-ouadid-benabdelaziz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        resources:
          requests:
            cpu: "4m"
            memory: "32Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-redis
  namespace: chegueni-ouadid-benabdelaziz
spec:
  selector:
    app: redis
  ports:
  - port: 6379

---
# 2. RabbitMQ (ReplicaSet + Service)
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rabbitmq-rs
  namespace: chegueni-ouadid-benabdelaziz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12-management
        resources:
          requests:
            cpu: "100m"  
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-rabbitmq
  namespace: chegueni-ouadid-benabdelaziz
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
  - name: management
    port: 15672

---
# 3. Backend / API (ReplicaSet + Service)
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: api-rs
  namespace: chegueni-ouadid-benabdelaziz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: ecr-registry
      containers:
      - name: backend
        image: 294337989672.dkr.ecr.eu-west-3.amazonaws.com/backend:latest
        env:
        - name: REDIS_HOST
          value: "svc-redis"
        - name: RABBITMQ_HOST
          value: "svc-rabbitmq"
        resources:
          requests:
            cpu: "4m"
            memory: "32Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-api
  namespace: chegueni-ouadid-benabdelaziz
spec:
  selector:
    app: backend
  ports:
  - port: 5000

---
# 4. Consumer (ReplicaSet)
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: consumer-rs
  namespace: chegueni-ouadid-benabdelaziz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      imagePullSecrets:
      - name: ecr-registry
      containers:
      - name: consumer
        image: 294337989672.dkr.ecr.eu-west-3.amazonaws.com/consumer:latest
        env:
        - name: REDIS_HOST
          value: "svc-redis"
        - name: RABBITMQ_HOST
          value: "svc-rabbitmq"
        resources:
          requests:
            cpu: "4m"
            memory: "32Mi"

---
# 5. Frontend (ReplicaSet + Service)
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: front-rs
  namespace: chegueni-ouadid-benabdelaziz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
      - name: ecr-registry
      containers:
      - name: frontend
        image: 294337989672.dkr.ecr.eu-west-3.amazonaws.com/frontend:latest
        resources:
          requests:
            cpu: "4m"
            memory: "32Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-front
  namespace: chegueni-ouadid-benabdelaziz
spec:
  selector:
    app: frontend
  ports:
  - port: 80

---
# 6. Ingress (الباب الرئيسي للمشروع)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: calculator-ingress
  namespace: chegueni-ouadid-benabdelaziz
spec:
  ingressClassName: nginx  # 
  rules:
  - host: calculatrice-chegueni-ouadid-benabdelaziz.polytech-dijon.kiowy.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-front
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: svc-api
            port:
              number: 5000
